version: "3.7"

services:
  muxia_bot:
    build: .
    container_name: muxia_bot
    restart: always
    environment:
      TELEGRAM_BOT_TOKEN: <your_bot_token>
    deploy:
      resources:
        limits:
          cpus: '0.80'
